apiVersion: v1
kind: Secret
metadata:
  name: ticketing-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgres://ticketing:CHANGE_ME@postgres:5432/ticketing"
  RABBITMQ_URL: "amqp://ticketing:CHANGE_ME@rabbitmq:5672"
  JWT_SECRET: "CHANGE_ME_TO_AT_LEAST_32_RANDOM_CHARACTERS"
  POSTGRES_USER: "ticketing"
  POSTGRES_PASSWORD: "CHANGE_ME"
  POSTGRES_DB: "ticketing"
  RABBITMQ_DEFAULT_USER: "ticketing"
  RABBITMQ_DEFAULT_PASS: "CHANGE_ME"
