DROP SCHEMA IF EXISTS notification CASCADE;
DROP SCHEMA IF EXISTS messaging CASCADE;
DROP SCHEMA IF EXISTS checkout CASCADE;
DROP SCHEMA IF EXISTS reservation CASCADE;
DROP SCHEMA IF EXISTS catalog CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;
